//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWPF.ServiceAgence {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteresRechercheBiensImmobiliers", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CriteresRechercheBiensImmobiliers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseContientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateMiseEnTransaction1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateMiseEnTransaction2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateTransaction1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateTransaction2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionContientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eEnergieChauffage> EnergieChauffageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontantCharges1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontantCharges2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbEtages1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbEtages2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPieces1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPieces2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumEtage1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumEtage2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Prix1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Prix2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Surface1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Surface2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreContientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TransactionEffectueeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers.Tri> TrisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eTypeBien> TypeBienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eTypeChauffage> TypeChauffageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eTypeTransaction> TypeTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdresseContient {
            get {
                return this.AdresseContientField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseContientField, value) != true)) {
                    this.AdresseContientField = value;
                    this.RaisePropertyChanged("AdresseContient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodePostal {
            get {
                return this.CodePostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePostalField, value) != true)) {
                    this.CodePostalField = value;
                    this.RaisePropertyChanged("CodePostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateMiseEnTransaction1 {
            get {
                return this.DateMiseEnTransaction1Field;
            }
            set {
                if ((this.DateMiseEnTransaction1Field.Equals(value) != true)) {
                    this.DateMiseEnTransaction1Field = value;
                    this.RaisePropertyChanged("DateMiseEnTransaction1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateMiseEnTransaction2 {
            get {
                return this.DateMiseEnTransaction2Field;
            }
            set {
                if ((this.DateMiseEnTransaction2Field.Equals(value) != true)) {
                    this.DateMiseEnTransaction2Field = value;
                    this.RaisePropertyChanged("DateMiseEnTransaction2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTransaction1 {
            get {
                return this.DateTransaction1Field;
            }
            set {
                if ((this.DateTransaction1Field.Equals(value) != true)) {
                    this.DateTransaction1Field = value;
                    this.RaisePropertyChanged("DateTransaction1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTransaction2 {
            get {
                return this.DateTransaction2Field;
            }
            set {
                if ((this.DateTransaction2Field.Equals(value) != true)) {
                    this.DateTransaction2Field = value;
                    this.RaisePropertyChanged("DateTransaction2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionContient {
            get {
                return this.DescriptionContientField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionContientField, value) != true)) {
                    this.DescriptionContientField = value;
                    this.RaisePropertyChanged("DescriptionContient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eEnergieChauffage> EnergieChauffage {
            get {
                return this.EnergieChauffageField;
            }
            set {
                if ((this.EnergieChauffageField.Equals(value) != true)) {
                    this.EnergieChauffageField = value;
                    this.RaisePropertyChanged("EnergieChauffage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontantCharges1 {
            get {
                return this.MontantCharges1Field;
            }
            set {
                if ((this.MontantCharges1Field.Equals(value) != true)) {
                    this.MontantCharges1Field = value;
                    this.RaisePropertyChanged("MontantCharges1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontantCharges2 {
            get {
                return this.MontantCharges2Field;
            }
            set {
                if ((this.MontantCharges2Field.Equals(value) != true)) {
                    this.MontantCharges2Field = value;
                    this.RaisePropertyChanged("MontantCharges2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbEtages1 {
            get {
                return this.NbEtages1Field;
            }
            set {
                if ((this.NbEtages1Field.Equals(value) != true)) {
                    this.NbEtages1Field = value;
                    this.RaisePropertyChanged("NbEtages1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbEtages2 {
            get {
                return this.NbEtages2Field;
            }
            set {
                if ((this.NbEtages2Field.Equals(value) != true)) {
                    this.NbEtages2Field = value;
                    this.RaisePropertyChanged("NbEtages2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPieces1 {
            get {
                return this.NbPieces1Field;
            }
            set {
                if ((this.NbPieces1Field.Equals(value) != true)) {
                    this.NbPieces1Field = value;
                    this.RaisePropertyChanged("NbPieces1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPieces2 {
            get {
                return this.NbPieces2Field;
            }
            set {
                if ((this.NbPieces2Field.Equals(value) != true)) {
                    this.NbPieces2Field = value;
                    this.RaisePropertyChanged("NbPieces2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEtage1 {
            get {
                return this.NumEtage1Field;
            }
            set {
                if ((this.NumEtage1Field.Equals(value) != true)) {
                    this.NumEtage1Field = value;
                    this.RaisePropertyChanged("NumEtage1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEtage2 {
            get {
                return this.NumEtage2Field;
            }
            set {
                if ((this.NumEtage2Field.Equals(value) != true)) {
                    this.NumEtage2Field = value;
                    this.RaisePropertyChanged("NumEtage2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prix1 {
            get {
                return this.Prix1Field;
            }
            set {
                if ((this.Prix1Field.Equals(value) != true)) {
                    this.Prix1Field = value;
                    this.RaisePropertyChanged("Prix1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prix2 {
            get {
                return this.Prix2Field;
            }
            set {
                if ((this.Prix2Field.Equals(value) != true)) {
                    this.Prix2Field = value;
                    this.RaisePropertyChanged("Prix2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Surface1 {
            get {
                return this.Surface1Field;
            }
            set {
                if ((this.Surface1Field.Equals(value) != true)) {
                    this.Surface1Field = value;
                    this.RaisePropertyChanged("Surface1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Surface2 {
            get {
                return this.Surface2Field;
            }
            set {
                if ((this.Surface2Field.Equals(value) != true)) {
                    this.Surface2Field = value;
                    this.RaisePropertyChanged("Surface2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitreContient {
            get {
                return this.TitreContientField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreContientField, value) != true)) {
                    this.TitreContientField = value;
                    this.RaisePropertyChanged("TitreContient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TransactionEffectuee {
            get {
                return this.TransactionEffectueeField;
            }
            set {
                if ((this.TransactionEffectueeField.Equals(value) != true)) {
                    this.TransactionEffectueeField = value;
                    this.RaisePropertyChanged("TransactionEffectuee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers.Tri> Tris {
            get {
                return this.TrisField;
            }
            set {
                if ((object.ReferenceEquals(this.TrisField, value) != true)) {
                    this.TrisField = value;
                    this.RaisePropertyChanged("Tris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eTypeBien> TypeBien {
            get {
                return this.TypeBienField;
            }
            set {
                if ((this.TypeBienField.Equals(value) != true)) {
                    this.TypeBienField = value;
                    this.RaisePropertyChanged("TypeBien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eTypeChauffage> TypeChauffage {
            get {
                return this.TypeChauffageField;
            }
            set {
                if ((this.TypeChauffageField.Equals(value) != true)) {
                    this.TypeChauffageField = value;
                    this.RaisePropertyChanged("TypeChauffage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ClientWPF.ServiceAgence.BienImmobilierBase.eTypeTransaction> TypeTransaction {
            get {
                return this.TypeTransactionField;
            }
            set {
                if ((this.TypeTransactionField.Equals(value) != true)) {
                    this.TypeTransactionField = value;
                    this.RaisePropertyChanged("TypeTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CriteresRechercheBiensImmobiliers.Tri", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        [System.SerializableAttribute()]
        public partial struct Tri : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers.eChampTri ChampField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers.eOrdreTri OrdreField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers.eChampTri Champ {
                get {
                    return this.ChampField;
                }
                set {
                    if ((this.ChampField.Equals(value) != true)) {
                        this.ChampField = value;
                        this.RaisePropertyChanged("Champ");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers.eOrdreTri Ordre {
                get {
                    return this.OrdreField;
                }
                set {
                    if ((this.OrdreField.Equals(value) != true)) {
                        this.OrdreField = value;
                        this.RaisePropertyChanged("Ordre");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CriteresRechercheBiensImmobiliers.eChampTri", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        public enum eChampTri : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Id = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Titre = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TypeTransaction = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TypeBien = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Description = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Prix = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MontantCharges = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DateMiseEnTransaction = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TransactionEffectuee = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DateTransaction = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Surface = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NbPieces = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NumEtage = 12,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NbEtages = 13,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TypeChauffage = 14,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EnergieChauffage = 15,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Adresse = 16,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CodePostal = 17,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ville = 18,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CriteresRechercheBiensImmobiliers.eOrdreTri", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        public enum eOrdreTri : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Montant = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Descendant = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BienImmobilierBase", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWPF.ServiceAgence.BienImmobilier))]
    public partial class BienImmobilierBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateMiseEnTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontantChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPrincipaleBase64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TransactionEffectueeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.ServiceAgence.BienImmobilierBase.eTypeBien TypeBienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.ServiceAgence.BienImmobilierBase.eTypeTransaction TypeTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodePostal {
            get {
                return this.CodePostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePostalField, value) != true)) {
                    this.CodePostalField = value;
                    this.RaisePropertyChanged("CodePostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateMiseEnTransaction {
            get {
                return this.DateMiseEnTransactionField;
            }
            set {
                if ((this.DateMiseEnTransactionField.Equals(value) != true)) {
                    this.DateMiseEnTransactionField = value;
                    this.RaisePropertyChanged("DateMiseEnTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTransaction {
            get {
                return this.DateTransactionField;
            }
            set {
                if ((this.DateTransactionField.Equals(value) != true)) {
                    this.DateTransactionField = value;
                    this.RaisePropertyChanged("DateTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontantCharges {
            get {
                return this.MontantChargesField;
            }
            set {
                if ((this.MontantChargesField.Equals(value) != true)) {
                    this.MontantChargesField = value;
                    this.RaisePropertyChanged("MontantCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPrincipaleBase64 {
            get {
                return this.PhotoPrincipaleBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPrincipaleBase64Field, value) != true)) {
                    this.PhotoPrincipaleBase64Field = value;
                    this.RaisePropertyChanged("PhotoPrincipaleBase64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prix {
            get {
                return this.PrixField;
            }
            set {
                if ((this.PrixField.Equals(value) != true)) {
                    this.PrixField = value;
                    this.RaisePropertyChanged("Prix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TransactionEffectuee {
            get {
                return this.TransactionEffectueeField;
            }
            set {
                if ((this.TransactionEffectueeField.Equals(value) != true)) {
                    this.TransactionEffectueeField = value;
                    this.RaisePropertyChanged("TransactionEffectuee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.ServiceAgence.BienImmobilierBase.eTypeBien TypeBien {
            get {
                return this.TypeBienField;
            }
            set {
                if ((this.TypeBienField.Equals(value) != true)) {
                    this.TypeBienField = value;
                    this.RaisePropertyChanged("TypeBien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.ServiceAgence.BienImmobilierBase.eTypeTransaction TypeTransaction {
            get {
                return this.TypeTransactionField;
            }
            set {
                if ((this.TypeTransactionField.Equals(value) != true)) {
                    this.TypeTransactionField = value;
                    this.RaisePropertyChanged("TypeTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="BienImmobilierBase.eEnergieChauffage", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        public enum eEnergieChauffage : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Aucun = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Fioul = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Gaz = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Electrique = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Bois = 4,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="BienImmobilierBase.eTypeBien", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        public enum eTypeBien : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Appartement = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Maison = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Garage = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Terrain = 3,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="BienImmobilierBase.eTypeChauffage", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        public enum eTypeChauffage : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Aucun = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Individuel = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Collectif = 2,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="BienImmobilierBase.eTypeTransaction", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        public enum eTypeTransaction : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Vente = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Location = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatOperation", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWPF.ServiceAgence.ResultatBienImmobilier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWPF.ServiceAgence.ResultatBool))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWPF.ServiceAgence.ResultatListeBiensImmobiliers))]
    public partial class ResultatOperation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClientWPF.ServiceAgence.ResultatOperation.Erreur> ErreursBloquantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClientWPF.ServiceAgence.ResultatOperation.Erreur> ErreursNonBloquantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccesExecutionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClientWPF.ServiceAgence.ResultatOperation.Erreur> ErreursBloquantes {
            get {
                return this.ErreursBloquantesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErreursBloquantesField, value) != true)) {
                    this.ErreursBloquantesField = value;
                    this.RaisePropertyChanged("ErreursBloquantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClientWPF.ServiceAgence.ResultatOperation.Erreur> ErreursNonBloquantes {
            get {
                return this.ErreursNonBloquantesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErreursNonBloquantesField, value) != true)) {
                    this.ErreursNonBloquantesField = value;
                    this.RaisePropertyChanged("ErreursNonBloquantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuccesExecution {
            get {
                return this.SuccesExecutionField;
            }
            set {
                if ((this.SuccesExecutionField.Equals(value) != true)) {
                    this.SuccesExecutionField = value;
                    this.RaisePropertyChanged("SuccesExecution");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ResultatOperation.Erreur", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        [System.SerializableAttribute()]
        public partial class Erreur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string MessageField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private ClientWPF.ServiceAgence.ResultatOperation.eTypeErreur TypeField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Message {
                get {
                    return this.MessageField;
                }
                set {
                    if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                        this.MessageField = value;
                        this.RaisePropertyChanged("Message");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public ClientWPF.ServiceAgence.ResultatOperation.eTypeErreur Type {
                get {
                    return this.TypeField;
                }
                set {
                    if ((this.TypeField.Equals(value) != true)) {
                        this.TypeField = value;
                        this.RaisePropertyChanged("Type");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ResultatOperation.eTypeErreur", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
        public enum eTypeErreur : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ErreurNonBloquante = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ErreurBloquante = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatBienImmobilier", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResultatBienImmobilier : ClientWPF.ServiceAgence.ResultatOperation {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.ServiceAgence.BienImmobilier BienField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.ServiceAgence.BienImmobilier Bien {
            get {
                return this.BienField;
            }
            set {
                if ((object.ReferenceEquals(this.BienField, value) != true)) {
                    this.BienField = value;
                    this.RaisePropertyChanged("Bien");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatBool", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResultatBool : ClientWPF.ServiceAgence.ResultatOperation {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValeurField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valeur {
            get {
                return this.ValeurField;
            }
            set {
                if ((this.ValeurField.Equals(value) != true)) {
                    this.ValeurField = value;
                    this.RaisePropertyChanged("Valeur");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatListeBiensImmobiliers", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResultatListeBiensImmobiliers : ClientWPF.ServiceAgence.ResultatOperation {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.ServiceAgence.ListeBiensImmobiliers ListeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.ServiceAgence.ListeBiensImmobiliers Liste {
            get {
                return this.ListeField;
            }
            set {
                if ((object.ReferenceEquals(this.ListeField, value) != true)) {
                    this.ListeField = value;
                    this.RaisePropertyChanged("Liste");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListeBiensImmobiliers", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ListeBiensImmobiliers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClientWPF.ServiceAgence.BienImmobilierBase> ListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagesCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SelectCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TakeCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClientWPF.ServiceAgence.BienImmobilierBase> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PagesCount {
            get {
                return this.PagesCountField;
            }
            set {
                if ((this.PagesCountField.Equals(value) != true)) {
                    this.PagesCountField = value;
                    this.RaisePropertyChanged("PagesCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SelectCount {
            get {
                return this.SelectCountField;
            }
            set {
                if ((this.SelectCountField.Equals(value) != true)) {
                    this.SelectCountField = value;
                    this.RaisePropertyChanged("SelectCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TakeCount {
            get {
                return this.TakeCountField;
            }
            set {
                if ((this.TakeCountField.Equals(value) != true)) {
                    this.TakeCountField = value;
                    this.RaisePropertyChanged("TakeCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BienImmobilier", Namespace="http://schemas.datacontract.org/2004/07/ServiceWCF.DataContracts")]
    [System.SerializableAttribute()]
    public partial class BienImmobilier : ClientWPF.ServiceAgence.BienImmobilierBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.ServiceAgence.BienImmobilierBase.eEnergieChauffage EnergieChauffageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbEtagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumEtageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> PhotosBase64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SurfaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.ServiceAgence.BienImmobilierBase.eTypeChauffage TypeChauffageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.ServiceAgence.BienImmobilierBase.eEnergieChauffage EnergieChauffage {
            get {
                return this.EnergieChauffageField;
            }
            set {
                if ((this.EnergieChauffageField.Equals(value) != true)) {
                    this.EnergieChauffageField = value;
                    this.RaisePropertyChanged("EnergieChauffage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbEtages {
            get {
                return this.NbEtagesField;
            }
            set {
                if ((this.NbEtagesField.Equals(value) != true)) {
                    this.NbEtagesField = value;
                    this.RaisePropertyChanged("NbEtages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPieces {
            get {
                return this.NbPiecesField;
            }
            set {
                if ((this.NbPiecesField.Equals(value) != true)) {
                    this.NbPiecesField = value;
                    this.RaisePropertyChanged("NbPieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEtage {
            get {
                return this.NumEtageField;
            }
            set {
                if ((this.NumEtageField.Equals(value) != true)) {
                    this.NumEtageField = value;
                    this.RaisePropertyChanged("NumEtage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> PhotosBase64 {
            get {
                return this.PhotosBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhotosBase64Field, value) != true)) {
                    this.PhotosBase64Field = value;
                    this.RaisePropertyChanged("PhotosBase64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Surface {
            get {
                return this.SurfaceField;
            }
            set {
                if ((this.SurfaceField.Equals(value) != true)) {
                    this.SurfaceField = value;
                    this.RaisePropertyChanged("Surface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.ServiceAgence.BienImmobilierBase.eTypeChauffage TypeChauffage {
            get {
                return this.TypeChauffageField;
            }
            set {
                if ((this.TypeChauffageField.Equals(value) != true)) {
                    this.TypeChauffageField = value;
                    this.RaisePropertyChanged("TypeChauffage");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgence.IAgence")]
    public interface IAgence {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/LireListeBiensImmobiliers", ReplyAction="http://tempuri.org/IAgence/LireListeBiensImmobiliersResponse")]
        ClientWPF.ServiceAgence.ResultatListeBiensImmobiliers LireListeBiensImmobiliers(ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers criteres, System.Nullable<int> page, System.Nullable<int> nbBiens);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/LireListeBiensImmobiliers", ReplyAction="http://tempuri.org/IAgence/LireListeBiensImmobiliersResponse")]
        System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatListeBiensImmobiliers> LireListeBiensImmobiliersAsync(ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers criteres, System.Nullable<int> page, System.Nullable<int> nbBiens);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/LireDetailsBienImmobilier", ReplyAction="http://tempuri.org/IAgence/LireDetailsBienImmobilierResponse")]
        ClientWPF.ServiceAgence.ResultatBienImmobilier LireDetailsBienImmobilier(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/LireDetailsBienImmobilier", ReplyAction="http://tempuri.org/IAgence/LireDetailsBienImmobilierResponse")]
        System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBienImmobilier> LireDetailsBienImmobilierAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/AjouterBienImmobilier", ReplyAction="http://tempuri.org/IAgence/AjouterBienImmobilierResponse")]
        ClientWPF.ServiceAgence.ResultatBool AjouterBienImmobilier(ClientWPF.ServiceAgence.BienImmobilier bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/AjouterBienImmobilier", ReplyAction="http://tempuri.org/IAgence/AjouterBienImmobilierResponse")]
        System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBool> AjouterBienImmobilierAsync(ClientWPF.ServiceAgence.BienImmobilier bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/ModifierBienImmobilier", ReplyAction="http://tempuri.org/IAgence/ModifierBienImmobilierResponse")]
        ClientWPF.ServiceAgence.ResultatBool ModifierBienImmobilier(ClientWPF.ServiceAgence.BienImmobilier bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/ModifierBienImmobilier", ReplyAction="http://tempuri.org/IAgence/ModifierBienImmobilierResponse")]
        System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBool> ModifierBienImmobilierAsync(ClientWPF.ServiceAgence.BienImmobilier bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/SupprimerBienImmobilier", ReplyAction="http://tempuri.org/IAgence/SupprimerBienImmobilierResponse")]
        ClientWPF.ServiceAgence.ResultatBool SupprimerBienImmobilier(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgence/SupprimerBienImmobilier", ReplyAction="http://tempuri.org/IAgence/SupprimerBienImmobilierResponse")]
        System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBool> SupprimerBienImmobilierAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgenceChannel : ClientWPF.ServiceAgence.IAgence, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgenceClient : System.ServiceModel.ClientBase<ClientWPF.ServiceAgence.IAgence>, ClientWPF.ServiceAgence.IAgence {
        
        public AgenceClient() {
        }
        
        public AgenceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgenceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientWPF.ServiceAgence.ResultatListeBiensImmobiliers LireListeBiensImmobiliers(ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers criteres, System.Nullable<int> page, System.Nullable<int> nbBiens) {
            return base.Channel.LireListeBiensImmobiliers(criteres, page, nbBiens);
        }
        
        public System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatListeBiensImmobiliers> LireListeBiensImmobiliersAsync(ClientWPF.ServiceAgence.CriteresRechercheBiensImmobiliers criteres, System.Nullable<int> page, System.Nullable<int> nbBiens) {
            return base.Channel.LireListeBiensImmobiliersAsync(criteres, page, nbBiens);
        }
        
        public ClientWPF.ServiceAgence.ResultatBienImmobilier LireDetailsBienImmobilier(string id) {
            return base.Channel.LireDetailsBienImmobilier(id);
        }
        
        public System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBienImmobilier> LireDetailsBienImmobilierAsync(string id) {
            return base.Channel.LireDetailsBienImmobilierAsync(id);
        }
        
        public ClientWPF.ServiceAgence.ResultatBool AjouterBienImmobilier(ClientWPF.ServiceAgence.BienImmobilier bien) {
            return base.Channel.AjouterBienImmobilier(bien);
        }
        
        public System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBool> AjouterBienImmobilierAsync(ClientWPF.ServiceAgence.BienImmobilier bien) {
            return base.Channel.AjouterBienImmobilierAsync(bien);
        }
        
        public ClientWPF.ServiceAgence.ResultatBool ModifierBienImmobilier(ClientWPF.ServiceAgence.BienImmobilier bien) {
            return base.Channel.ModifierBienImmobilier(bien);
        }
        
        public System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBool> ModifierBienImmobilierAsync(ClientWPF.ServiceAgence.BienImmobilier bien) {
            return base.Channel.ModifierBienImmobilierAsync(bien);
        }
        
        public ClientWPF.ServiceAgence.ResultatBool SupprimerBienImmobilier(string id) {
            return base.Channel.SupprimerBienImmobilier(id);
        }
        
        public System.Threading.Tasks.Task<ClientWPF.ServiceAgence.ResultatBool> SupprimerBienImmobilierAsync(string id) {
            return base.Channel.SupprimerBienImmobilierAsync(id);
        }
    }
}
