<%@ Page Title="" Language="C#" MasterPageFile="~/General.Master" AutoEventWireup="true" CodeBehind="admin.aspx.cs" Inherits="ClientWeb.admin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="mLabel" runat="server" Text="Label"></asp:Label>


      <asp:GridView ID="gvResultats" runat="server" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowEditing="TaskGridView_RowEditing" OnRowCancelingEdit="TaskGridView_RowCancelingEdit" OnRowUpdating="TaskGridView_RowUpdating"> 
        <Columns>
            
            
        </Columns>
    </asp:GridView>

    
</asp:Content>
